### PR TITLE
Heliopsis

### PR DESCRIPTION
**Pull request by bchoquet-heliopsis**
Hi, here are a few updates I made while using the extension :

Bugfix :
- getting valid limitations values for SiteAccess and Subtree limitations in CreateRoleHandler

Improvements :
- remoteID handling in referenceIDs for getting object_id or main_node_id from remote_id
- Call to getReferenceID() for CreateContentHandler parentNodeID

Hope you'll find it useful

### CODE REVIEW

**Comment by nfrp** [comment]
From what i can see here : http://projects.ez.no/ezxmlinstaller the current trunk will end-up being 0.1.5, meaning the @since tag should be : 
    @since 0.1.5

@Andre : do you confirm ?

Cheers!

**Comment by andrerom** [comment]
No, I cannot. ezinfo.php says 1.0 and version info on ci says 1.1.0. And since version info in current download for 4.4 says 1.1.0 as well, next is 1.2.0

**Comment by bchoquet-heliopsis** [comment]
1.2.0 it is.
I commited the requested changes (0434853429dcda948777ae0e65e16e8a3293d013) and added it to the pull request

**Comment by bchoquet-heliopsis** [comment]
You're quite hard boiled considering the initial code was not documented at all ;)
Anyway thanks for the config tips, I think it should be alright this time

**Comment by andrerom** [comment]
Past sins does not make future sins more acceptable :P

Anyway, applied the code now and notified QA, thanks very much for your contribution and for hanging in there on all iterations. Better online docs on code standard and so on are in our pipeline :)

**Pull request closed without merging**
