### PR TITLE
Addlocation improvements

### PR DESCRIPTION
**Pull request by bchoquet-heliopsis**
Two new features for the AddLocation handler :
- allow to add an internal reference to new location
- allow to set new node priority

### CODE REVIEW

**Comment by nfrp** [comment]
I see no reason why this should not be integrated. 
I believe you tested the cases where the reference and priority XML attributes are not set ?

Cheers,

**Comment by bchoquet-heliopsis** [comment]
`DOMElement::getAttribute` defaults to an empty string if not set. The if clause returns false in this case.

**Comment by nfrp** [comment]
Ok, seems all safe then. Merging now.

**Comment by nfrp** [comment]
Thanks a lot Benjamin, keep them coming !

**Pull request merged**
